Run backend code checker

diff --git a/update b/update
--- a/update
+++ b/update
@@ -6,12 +6,43 @@ git show $newrev > commitFile$newrev.txt
 file=commitFile$newrev.txt
 while read -r line
 do
-    if [[ "$line" == diff* ]] ; then toextract=false ; fi
-    if [[ "$line" == @@* ]] ; then toextract=true ; fi 
-    
-    # content to be output to JS file
-    if [ "$toextract" = true ] && [[ "$line" != @@* ]] && [[ "$line" != -* ]] ; then
-        echo $line | sed 's/^.//'>> input.js  #remove first character
+    # signifies the ends of code
+    if [[ "$line" == diff* ]]; then
+        # runs code runner before going to new section of codes
+        if [[ "$toextract" == true ]]; then
+            result=$(node ./backend_code_runner/backend_code_runner.js)
+            if [ "${result: -2}" != "ok" ] ; then
+                # Unit tests fails
+                echo Fail to Pass all Unit Tests.
+                rm input.js
+                exit 1
+            fi
+
+            # if all unit tests pass, clear the file
+            > input.js
+        fi
+
+        toextract=false
     fi
 
+    # signifies the next line will be the codes
+    if [[ "$line" == @@* ]] ; then toextract=true ; fi
+
+    # output the codes to the file input.js
+    if [ "$toextract" == true ] && [[ "$line" != @@* ]] && [[ "$line" != -* ]] ; then
+        echo "$line" | sed 's/^.//'>> input.js  #remove first character
+    fi
 done < $file
+
+# runs code runner for the last section of codes
+result=$(node ./backend_code_runner/backend_code_runner.js)
+
+if [ "${result: -2}" != "ok" ] ; then
+    echo Fail to Pass all Unit Tests.
+    rm input.js
+    exit 1
+fi
+
+echo All Unit Test Passes.
+rm input.js
+exit 0
